// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function callerClient(ctx) {
  const token = ctx.getToken();
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: token ? { headers: { Authorization: `Bearer ${token}` } } : void 0
  });
}
function unauthorized() {
  return {
    content: [{ type: "text", text: "You must be signed in to use this tool." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts from Daryl Tech Educational Network. Requires sign-in.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 10)."),
    category: z.string().optional().describe("Filter by category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const supabase = callerClient(ctx);
    let q = supabase.from("blog_posts").select("id,title,excerpt,category,author_name,read_time,created_at").eq("published", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full content of a single published blog post by id. Requires sign-in.",
  inputSchema: { id: z2.string().uuid().describe("Blog post id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const supabase = callerClient(ctx);
    const { data, error } = await supabase.from("blog_posts").select("*").eq("id", id).eq("published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Post not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/verify-certificate.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var verify_certificate_default = defineTool3({
  name: "verify_certificate",
  title: "Verify certificate",
  description: "Verify a DTEN certificate by enrollment ID (starts with DTEN-). Requires sign-in. Returns only a validity result and the course/type unless the certificate belongs to the signed-in account.",
  inputSchema: { enrollment_id: z3.string().min(3).describe("Enrollment ID, e.g. DTEN-XXXX.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ enrollment_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const userId = ctx.getUserId();
    if (!userId) return unauthorized();
    const supabase = callerClient(ctx);
    const { data, error } = await supabase.from("certificates").select("enrollment_id,student_name,course,type,issued_date,issued_by,description").eq("enrollment_id", enrollment_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return {
        content: [{ type: "text", text: `No certificate found for ${enrollment_id}.` }],
        structuredContent: { valid: false, certificates: [] }
      };
    }
    const [{ data: ownEnrollment }, { data: isAdmin }] = await Promise.all([
      supabase.from("enrollments").select("enrollment_id").eq("enrollment_id", enrollment_id).eq("user_id", userId).maybeSingle(),
      supabase.rpc("has_role", { _user_id: userId, _role: "admin" })
    ]);
    const privileged = Boolean(ownEnrollment) || isAdmin === true;
    if (!privileged) {
      const redacted = data.map((c) => ({ course: c.course, type: c.type }));
      return {
        content: [
          {
            type: "text",
            text: `Certificate for ${enrollment_id} is valid. Details are hidden because this certificate does not belong to your account.
${JSON.stringify(redacted, null, 2)}`
          }
        ],
        structuredContent: { valid: true, redacted: true, certificates: redacted }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { valid: true, redacted: false, certificates: data }
    };
  }
});

// src/lib/mcp/tools/submit-internship-application.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_internship_application_default = defineTool4({
  name: "submit_internship_application",
  title: "Submit internship application",
  description: "Submit an internship application to Daryl Tech Educational Network. Requires sign-in.",
  inputSchema: {
    full_name: z4.string().min(2).max(100),
    email: z4.string().email(),
    phone: z4.string().max(30).optional(),
    track: z4.string().min(2).describe("Desired internship track (e.g. Web Development)."),
    experience_level: z4.string().describe("Beginner, Intermediate, or Advanced."),
    portfolio_url: z4.string().url().optional(),
    motivation: z4.string().min(20).max(1500).describe("Why you want this internship.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const supabase = callerClient(ctx);
    const { data, error } = await supabase.from("internship_applications").insert(input).select("id,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Application submitted. Reference: ${data.id}` }],
      structuredContent: { application_id: data.id, created_at: data.created_at }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dten-mcp",
  title: "Daryl Tech Educational Network",
  version: "0.1.0",
  instructions: "Tools for Daryl Tech Educational Network (DTEN): browse published blog posts, verify student certificates by enrollment ID (DTEN-...), and submit internship applications. Every tool runs as the signed-in DTEN account and only returns data that account is allowed to see.",
  auth: auth.oauth.issuer({
    issuer: "https://rruwxmfanmrhicfcoenx.supabase.co/auth/v1",
    acceptedAudiences: ["authenticated"],
    resourceName: "Daryl Tech Educational Network"
  }),
  tools: [list_blog_posts_default, get_blog_post_default, verify_certificate_default, submit_internship_application_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
